// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: dependency.proto

package word_segment_grpc_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	GovIdx        int32                  `protobuf:"varint,2,opt,name=gov_idx,json=govIdx,proto3" json:"gov_idx,omitempty"`
	Rel           string                 `protobuf:"bytes,3,opt,name=rel,proto3" json:"rel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_dependency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{0}
}

func (x *Dependency) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Dependency) GetGovIdx() int32 {
	if x != nil {
		return x.GovIdx
	}
	return 0
}

func (x *Dependency) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

type DependencyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []*Dependency          `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyList) Reset() {
	*x = DependencyList{}
	mi := &file_dependency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyList) ProtoMessage() {}

func (x *DependencyList) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyList.ProtoReflect.Descriptor instead.
func (*DependencyList) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{1}
}

func (x *DependencyList) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type ParseDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDependenciesRequest) Reset() {
	*x = ParseDependenciesRequest{}
	mi := &file_dependency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDependenciesRequest) ProtoMessage() {}

func (x *ParseDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDependenciesRequest.ProtoReflect.Descriptor instead.
func (*ParseDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{2}
}

func (x *ParseDependenciesRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ParseDependenciesRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ParseDependenciesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DependencyList []*DependencyList      `protobuf:"bytes,1,rep,name=dependency_list,json=dependencyList,proto3" json:"dependency_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseDependenciesResponse) Reset() {
	*x = ParseDependenciesResponse{}
	mi := &file_dependency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDependenciesResponse) ProtoMessage() {}

func (x *ParseDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dependency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDependenciesResponse.ProtoReflect.Descriptor instead.
func (*ParseDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_dependency_proto_rawDescGZIP(), []int{3}
}

func (x *ParseDependenciesResponse) GetDependencyList() []*DependencyList {
	if x != nil {
		return x.DependencyList
	}
	return nil
}

var File_dependency_proto protoreflect.FileDescriptor

var file_dependency_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x4b,
	0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x6f, 0x76, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x67, 0x6f, 0x76, 0x49, 0x64, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x6c, 0x22, 0x4c, 0x0a, 0x0e, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a,
	0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79,
	0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0c, 0x64, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x22, 0x42, 0x0a, 0x18, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x60, 0x0a,
	0x19, 0x50, 0x61, 0x72, 0x73, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x64, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79,
	0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x0e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x32,
	0x75, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x50, 0x61, 0x72, 0x73, 0x65, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x64, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x32, 0x30, 0x32, 0x34,
	0x2f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_dependency_proto_rawDescOnce sync.Once
	file_dependency_proto_rawDescData []byte
)

func file_dependency_proto_rawDescGZIP() []byte {
	file_dependency_proto_rawDescOnce.Do(func() {
		file_dependency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dependency_proto_rawDesc), len(file_dependency_proto_rawDesc)))
	})
	return file_dependency_proto_rawDescData
}

var file_dependency_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dependency_proto_goTypes = []any{
	(*Dependency)(nil),                // 0: dependency.Dependency
	(*DependencyList)(nil),            // 1: dependency.DependencyList
	(*ParseDependenciesRequest)(nil),  // 2: dependency.ParseDependenciesRequest
	(*ParseDependenciesResponse)(nil), // 3: dependency.ParseDependenciesResponse
}
var file_dependency_proto_depIdxs = []int32{
	0, // 0: dependency.DependencyList.dependencies:type_name -> dependency.Dependency
	1, // 1: dependency.ParseDependenciesResponse.dependency_list:type_name -> dependency.DependencyList
	2, // 2: dependency.DependencyService.ParseDependencies:input_type -> dependency.ParseDependenciesRequest
	3, // 3: dependency.DependencyService.ParseDependencies:output_type -> dependency.ParseDependenciesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dependency_proto_init() }
func file_dependency_proto_init() {
	if File_dependency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dependency_proto_rawDesc), len(file_dependency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dependency_proto_goTypes,
		DependencyIndexes: file_dependency_proto_depIdxs,
		MessageInfos:      file_dependency_proto_msgTypes,
	}.Build()
	File_dependency_proto = out.File
	file_dependency_proto_goTypes = nil
	file_dependency_proto_depIdxs = nil
}
