// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: segment.proto

package word_segment_grpc_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WordSegmentation_Segment_FullMethodName = "/word_segmentation.WordSegmentation/Segment"
)

// WordSegmentationClient is the client API for WordSegmentation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordSegmentationClient interface {
	Segment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
}

type wordSegmentationClient struct {
	cc grpc.ClientConnInterface
}

func NewWordSegmentationClient(cc grpc.ClientConnInterface) WordSegmentationClient {
	return &wordSegmentationClient{cc}
}

func (c *wordSegmentationClient) Segment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, WordSegmentation_Segment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordSegmentationServer is the server API for WordSegmentation service.
// All implementations must embed UnimplementedWordSegmentationServer
// for forward compatibility.
type WordSegmentationServer interface {
	Segment(context.Context, *SegmentRequest) (*SegmentResponse, error)
	mustEmbedUnimplementedWordSegmentationServer()
}

// UnimplementedWordSegmentationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWordSegmentationServer struct{}

func (UnimplementedWordSegmentationServer) Segment(context.Context, *SegmentRequest) (*SegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Segment not implemented")
}
func (UnimplementedWordSegmentationServer) mustEmbedUnimplementedWordSegmentationServer() {}
func (UnimplementedWordSegmentationServer) testEmbeddedByValue()                          {}

// UnsafeWordSegmentationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordSegmentationServer will
// result in compilation errors.
type UnsafeWordSegmentationServer interface {
	mustEmbedUnimplementedWordSegmentationServer()
}

func RegisterWordSegmentationServer(s grpc.ServiceRegistrar, srv WordSegmentationServer) {
	// If the following call pancis, it indicates UnimplementedWordSegmentationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WordSegmentation_ServiceDesc, srv)
}

func _WordSegmentation_Segment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSegmentationServer).Segment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WordSegmentation_Segment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSegmentationServer).Segment(ctx, req.(*SegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordSegmentation_ServiceDesc is the grpc.ServiceDesc for WordSegmentation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordSegmentation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "word_segmentation.WordSegmentation",
	HandlerType: (*WordSegmentationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Segment",
			Handler:    _WordSegmentation_Segment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "segment.proto",
}
